POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Welcome Blog",
  "author": "audreyobrien",
  "url": "https://shop-grwm.com/outfit-ideas/welcome-blog/",
  "likes": 21
}